### ISSUE TITLE
Advanced OS boot parameters

### ISSUE THREAD

**Issue by wowi42** [vatesfr/xo#67] opened 2015-09-14 05:59 UTC
Hi Vates Team,

We are very happy about your product, but we are facing a small issue:

We want to install massively similar VMs, and for this, we want to automatically customize our VMs, like using anaconda, kickstart or AIF. 

Is there a way to have the option Advanced OS boot parameters: console=hvc0 utf8 noipv6 ks=http://aswtel.com/xxx/centos7-server.ks

Thanks a lot

**Comment by olivierlambert** [comment] 2015-09-14 07:10
Duplicate of https://github.com/vatesfr/xo-web/issues/112

**Closed by olivierlambert** 2015-09-14 07:10 UTC
