### ISSUE TITLE
Show tags assigned to VM

### ISSUE THREAD

**Issue by robkooper** [vatesfr/xo#63] opened 2015-08-06 18:11 UTC
It would be nice to have a way to see tags, and filter by tags. For example I add a bunch of tags to a machine using `xe vm-param-add uuid=<your_uuid> param-name=tags param-key=<new_tag>` and it would be nice to see these tags in XOA.

**Comment by olivierlambert** [comment] 2015-08-06 18:12
Yup, you are right!

**Comment by olivierlambert** [comment] 2015-09-14 07:11
Duplicate of https://github.com/vatesfr/xo-web/issues/367

**Closed by olivierlambert** 2015-09-14 07:11 UTC
Labels: enhancement
